/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const E8s = IDL.Nat;
export const DepositResult = IDL.Variant({ 'ok' : E8s, 'err' : IDL.Text });
export const GameCategory = IDL.Variant({
  'Slots' : IDL.Null,
  'CardGames' : IDL.Null,
  'TableGames' : IDL.Null,
});
export const Game = IDL.Record({
  'id' : IDL.Nat,
  'rtp' : IDL.Float64,
  'featured' : IDL.Bool,
  'name' : IDL.Text,
  'playerCount' : IDL.Nat,
  'imageUrl' : IDL.Text,
  'category' : GameCategory,
  'houseEdge' : IDL.Float64,
});
export const TransactionType = IDL.Variant({
  'Bet' : IDL.Null,
  'Deposit' : IDL.Null,
  'Winning' : IDL.Null,
});
export const Timestamp = IDL.Int;
export const Transaction = IDL.Record({
  'id' : IDL.Nat,
  'result' : IDL.Opt(IDL.Text),
  'netAmount' : IDL.Int,
  'transactionType' : TransactionType,
  'betAmount' : E8s,
  'gameId' : IDL.Opt(IDL.Nat),
  'timestamp' : Timestamp,
  'gameName' : IDL.Opt(IDL.Text),
});
export const PlaceBetRequest = IDL.Record({
  'betAmount' : E8s,
  'gameId' : IDL.Nat,
});
export const PlaceBetResult = IDL.Variant({
  'ok' : Transaction,
  'err' : IDL.Text,
});

export const idlService = IDL.Service({
  'deposit' : IDL.Func([E8s], [DepositResult], []),
  'getBalance' : IDL.Func([], [E8s], []),
  'getGame' : IDL.Func([IDL.Nat], [IDL.Opt(Game)], ['query']),
  'getTransactions' : IDL.Func(
      [IDL.Opt(TransactionType)],
      [IDL.Vec(Transaction)],
      [],
    ),
  'listFeaturedGames' : IDL.Func([], [IDL.Vec(Game)], ['query']),
  'listGames' : IDL.Func([], [IDL.Vec(Game)], ['query']),
  'listGamesByCategory' : IDL.Func([GameCategory], [IDL.Vec(Game)], ['query']),
  'placeBet' : IDL.Func([PlaceBetRequest], [PlaceBetResult], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const E8s = IDL.Nat;
  const DepositResult = IDL.Variant({ 'ok' : E8s, 'err' : IDL.Text });
  const GameCategory = IDL.Variant({
    'Slots' : IDL.Null,
    'CardGames' : IDL.Null,
    'TableGames' : IDL.Null,
  });
  const Game = IDL.Record({
    'id' : IDL.Nat,
    'rtp' : IDL.Float64,
    'featured' : IDL.Bool,
    'name' : IDL.Text,
    'playerCount' : IDL.Nat,
    'imageUrl' : IDL.Text,
    'category' : GameCategory,
    'houseEdge' : IDL.Float64,
  });
  const TransactionType = IDL.Variant({
    'Bet' : IDL.Null,
    'Deposit' : IDL.Null,
    'Winning' : IDL.Null,
  });
  const Timestamp = IDL.Int;
  const Transaction = IDL.Record({
    'id' : IDL.Nat,
    'result' : IDL.Opt(IDL.Text),
    'netAmount' : IDL.Int,
    'transactionType' : TransactionType,
    'betAmount' : E8s,
    'gameId' : IDL.Opt(IDL.Nat),
    'timestamp' : Timestamp,
    'gameName' : IDL.Opt(IDL.Text),
  });
  const PlaceBetRequest = IDL.Record({ 'betAmount' : E8s, 'gameId' : IDL.Nat });
  const PlaceBetResult = IDL.Variant({ 'ok' : Transaction, 'err' : IDL.Text });
  
  return IDL.Service({
    'deposit' : IDL.Func([E8s], [DepositResult], []),
    'getBalance' : IDL.Func([], [E8s], []),
    'getGame' : IDL.Func([IDL.Nat], [IDL.Opt(Game)], ['query']),
    'getTransactions' : IDL.Func(
        [IDL.Opt(TransactionType)],
        [IDL.Vec(Transaction)],
        [],
      ),
    'listFeaturedGames' : IDL.Func([], [IDL.Vec(Game)], ['query']),
    'listGames' : IDL.Func([], [IDL.Vec(Game)], ['query']),
    'listGamesByCategory' : IDL.Func(
        [GameCategory],
        [IDL.Vec(Game)],
        ['query'],
      ),
    'placeBet' : IDL.Func([PlaceBetRequest], [PlaceBetResult], []),
  });
};

export const init = ({ IDL }) => { return []; };