/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type DepositResult = { 'ok' : E8s } |
  { 'err' : string };
export type E8s = bigint;
export interface Game {
  'id' : bigint,
  'rtp' : number,
  'featured' : boolean,
  'name' : string,
  'playerCount' : bigint,
  'imageUrl' : string,
  'category' : GameCategory,
  'houseEdge' : number,
}
export type GameCategory = { 'Slots' : null } |
  { 'CardGames' : null } |
  { 'TableGames' : null };
export interface PlaceBetRequest { 'betAmount' : E8s, 'gameId' : bigint }
export type PlaceBetResult = { 'ok' : Transaction } |
  { 'err' : string };
export type Timestamp = bigint;
export interface Transaction {
  'id' : bigint,
  'result' : [] | [string],
  'netAmount' : bigint,
  'transactionType' : TransactionType,
  'betAmount' : E8s,
  'gameId' : [] | [bigint],
  'timestamp' : Timestamp,
  'gameName' : [] | [string],
}
export type TransactionType = { 'Bet' : null } |
  { 'Deposit' : null } |
  { 'Winning' : null };
export interface _SERVICE {
  'deposit' : ActorMethod<[E8s], DepositResult>,
  'getBalance' : ActorMethod<[], E8s>,
  'getGame' : ActorMethod<[bigint], [] | [Game]>,
  'getTransactions' : ActorMethod<[[] | [TransactionType]], Array<Transaction>>,
  'listFeaturedGames' : ActorMethod<[], Array<Game>>,
  'listGames' : ActorMethod<[], Array<Game>>,
  'listGamesByCategory' : ActorMethod<[GameCategory], Array<Game>>,
  'placeBet' : ActorMethod<[PlaceBetRequest], PlaceBetResult>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];