/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Transaction {
    id: bigint;
    result?: string;
    netAmount: bigint;
    transactionType: TransactionType;
    betAmount: E8s;
    gameId?: bigint;
    timestamp: Timestamp;
    gameName?: string;
}
export type Timestamp = bigint;
export interface Game {
    id: bigint;
    rtp: number;
    featured: boolean;
    name: string;
    playerCount: bigint;
    imageUrl: string;
    category: GameCategory;
    houseEdge: number;
}
export type E8s = bigint;
export type DepositResult = {
    __kind__: "ok";
    ok: E8s;
} | {
    __kind__: "err";
    err: string;
};
export interface PlaceBetRequest {
    betAmount: E8s;
    gameId: bigint;
}
export type PlaceBetResult = {
    __kind__: "ok";
    ok: Transaction;
} | {
    __kind__: "err";
    err: string;
};
export enum GameCategory {
    Slots = "Slots",
    CardGames = "CardGames",
    TableGames = "TableGames"
}
export enum TransactionType {
    Bet = "Bet",
    Deposit = "Deposit",
    Winning = "Winning"
}
export interface backendInterface {
    deposit(amount: E8s): Promise<DepositResult>;
    getBalance(): Promise<E8s>;
    getGame(gameId: bigint): Promise<Game | null>;
    getTransactions(typeFilter: TransactionType | null): Promise<Array<Transaction>>;
    listFeaturedGames(): Promise<Array<Game>>;
    listGames(): Promise<Array<Game>>;
    listGamesByCategory(category: GameCategory): Promise<Array<Game>>;
    placeBet(req: PlaceBetRequest): Promise<PlaceBetResult>;
}
import type { DepositResult as _DepositResult, E8s as _E8s, Game as _Game, GameCategory as _GameCategory, PlaceBetResult as _PlaceBetResult, Timestamp as _Timestamp, Transaction as _Transaction, TransactionType as _TransactionType } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async deposit(arg0: E8s): Promise<DepositResult> {
        if (this.processError) {
            try {
                const result = await this.actor.deposit(arg0);
                return from_candid_DepositResult_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deposit(arg0);
            return from_candid_DepositResult_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBalance(): Promise<E8s> {
        if (this.processError) {
            try {
                const result = await this.actor.getBalance();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBalance();
            return result;
        }
    }
    async getGame(arg0: bigint): Promise<Game | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getGame(arg0);
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGame(arg0);
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTransactions(arg0: TransactionType | null): Promise<Array<Transaction>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTransactions(to_candid_opt_n8(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTransactions(to_candid_opt_n8(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async listFeaturedGames(): Promise<Array<Game>> {
        if (this.processError) {
            try {
                const result = await this.actor.listFeaturedGames();
                return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listFeaturedGames();
            return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async listGames(): Promise<Array<Game>> {
        if (this.processError) {
            try {
                const result = await this.actor.listGames();
                return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listGames();
            return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async listGamesByCategory(arg0: GameCategory): Promise<Array<Game>> {
        if (this.processError) {
            try {
                const result = await this.actor.listGamesByCategory(to_candid_GameCategory_n19(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listGamesByCategory(to_candid_GameCategory_n19(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async placeBet(arg0: PlaceBetRequest): Promise<PlaceBetResult> {
        if (this.processError) {
            try {
                const result = await this.actor.placeBet(arg0);
                return from_candid_PlaceBetResult_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.placeBet(arg0);
            return from_candid_PlaceBetResult_n21(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_DepositResult_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DepositResult): DepositResult {
    return from_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function from_candid_GameCategory_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _GameCategory): GameCategory {
    return from_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function from_candid_Game_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Game): Game {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_PlaceBetResult_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PlaceBetResult): PlaceBetResult {
    return from_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function from_candid_TransactionType_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TransactionType): TransactionType {
    return from_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function from_candid_Transaction_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Transaction): Transaction {
    return from_candid_record_n13(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Game]): Game | null {
    return value.length === 0 ? null : from_candid_Game_n4(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    result: [] | [string];
    netAmount: bigint;
    transactionType: _TransactionType;
    betAmount: _E8s;
    gameId: [] | [bigint];
    timestamp: _Timestamp;
    gameName: [] | [string];
}): {
    id: bigint;
    result?: string;
    netAmount: bigint;
    transactionType: TransactionType;
    betAmount: E8s;
    gameId?: bigint;
    timestamp: Timestamp;
    gameName?: string;
} {
    return {
        id: value.id,
        result: record_opt_to_undefined(from_candid_opt_n14(_uploadFile, _downloadFile, value.result)),
        netAmount: value.netAmount,
        transactionType: from_candid_TransactionType_n15(_uploadFile, _downloadFile, value.transactionType),
        betAmount: value.betAmount,
        gameId: record_opt_to_undefined(from_candid_opt_n17(_uploadFile, _downloadFile, value.gameId)),
        timestamp: value.timestamp,
        gameName: record_opt_to_undefined(from_candid_opt_n14(_uploadFile, _downloadFile, value.gameName))
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    rtp: number;
    featured: boolean;
    name: string;
    playerCount: bigint;
    imageUrl: string;
    category: _GameCategory;
    houseEdge: number;
}): {
    id: bigint;
    rtp: number;
    featured: boolean;
    name: string;
    playerCount: bigint;
    imageUrl: string;
    category: GameCategory;
    houseEdge: number;
} {
    return {
        id: value.id,
        rtp: value.rtp,
        featured: value.featured,
        name: value.name,
        playerCount: value.playerCount,
        imageUrl: value.imageUrl,
        category: from_candid_GameCategory_n6(_uploadFile, _downloadFile, value.category),
        houseEdge: value.houseEdge
    };
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Bet: null;
} | {
    Deposit: null;
} | {
    Winning: null;
}): TransactionType {
    return "Bet" in value ? TransactionType.Bet : "Deposit" in value ? TransactionType.Deposit : "Winning" in value ? TransactionType.Winning : value;
}
function from_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _E8s;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: E8s;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _Transaction;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: Transaction;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_Transaction_n12(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Slots: null;
} | {
    CardGames: null;
} | {
    TableGames: null;
}): GameCategory {
    return "Slots" in value ? GameCategory.Slots : "CardGames" in value ? GameCategory.CardGames : "TableGames" in value ? GameCategory.TableGames : value;
}
function from_candid_vec_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Transaction>): Array<Transaction> {
    return value.map((x)=>from_candid_Transaction_n12(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Game>): Array<Game> {
    return value.map((x)=>from_candid_Game_n4(_uploadFile, _downloadFile, x));
}
function to_candid_GameCategory_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: GameCategory): _GameCategory {
    return to_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function to_candid_TransactionType_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TransactionType): _TransactionType {
    return to_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TransactionType | null): [] | [_TransactionType] {
    return value === null ? candid_none() : candid_some(to_candid_TransactionType_n9(_uploadFile, _downloadFile, value));
}
function to_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TransactionType): {
    Bet: null;
} | {
    Deposit: null;
} | {
    Winning: null;
} {
    return value == TransactionType.Bet ? {
        Bet: null
    } : value == TransactionType.Deposit ? {
        Deposit: null
    } : value == TransactionType.Winning ? {
        Winning: null
    } : value;
}
function to_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: GameCategory): {
    Slots: null;
} | {
    CardGames: null;
} | {
    TableGames: null;
} {
    return value == GameCategory.Slots ? {
        Slots: null
    } : value == GameCategory.CardGames ? {
        CardGames: null
    } : value == GameCategory.TableGames ? {
        TableGames: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
